networks:
    dcp:
        name: dcp
        external: true

services:
  mail-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - APP_NAME=MailService
    image: mail-service:latest
    container_name: mail-service
    ports:
        - "8081:8081"
    environment:
        - PORT=${PORT:-8081}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT:-25}
        - API_SERVICE_URL=${API_SERVICE_URL}
        - CHATGPT_SERVICE_URL=${CHATGPT_SERVICE_URL}
        - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
    env_file:
        - .env
    networks:
        - dcp

    # The below two services are for testing purposes only
    # They are required to test the application in a CI environment

  db:
      image: postgres:latest
      environment:
          POSTGRES_DB: testdb
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
          - "5432:5432"
      volumes:
          - postgres_data:/var/lib/postgresql/data
          - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
      env_file:
          - .env

  github-action-maven-test:
      build:
          context: .
          dockerfile: .github/workflows/Dockerfile
      depends_on:
          - db
      environment:
          - DB_HOST=db
          - DB_PORT=5432
          - DB_NAME=testdb
          - DB_USERNAME=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
      env_file:
          - .env
      command: ["mvn", "test", "-Dspring.profiles.active=test"]

volumes:
    postgres_data:
