server:
    port: ${PORT:8080}
    servlet:
        context-path: /

spring:
    application:
        name: mail-service
    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT:-2525}
        default:
            from: ${DEFAULT_FROM_MAIL_ID:noreply@dcp.com}
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    connectiontimeout: ${MAIL_CONNECTION_TIMEOUT:5000}
                    timeout: ${MAIL_TIMEOUT:5000}
                    writetimeout: ${MAIL_WRITE_TIMEOUT:5000}
    retry:
        max-attempts: ${RETRY_MAX_ATTEMPTS:3}
        max-delay: ${RETRY_MAX_DELAY:1000}

logging:
    level:
        root: INFO
        org.springframework.web: INFO

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:-*}
